#!/usr/bin/env python

import sys
from os.path import abspath, join, dirname, pardir

sys.path.insert(0, abspath(join(dirname(__file__), pardir)))
sys.path.insert(0, abspath(join(dirname(__file__), pardir, 'lib')))

from test.run import main

if __name__ == '__main__':
   main(sys.argv)
