#!/usr/bin/env python

import sys
from os.path import abspath, join, dirname, pardir

sys.path.insert(0, abspath(join(dirname(__file__), pardir, "build", "packages", "python")))

from lib.framework import run
from tests.all import tests

if __name__ == '__main__':
    run(tests, sys.argv[1:])
